### ISSUE TITLE
LocalDate and LocalDateTime serialization problem

### ISSUE THREAD

**Issue by dmarko484** [ravendb/jvm-client#11]
Hello,
we use  `java.time.LocalDate` and  `java.time.LocalDateTime` structures for Date(Time) representation in our projects and when storing into RavenDB we just realized , that it is serialized into non-date structure as below. Is there a way how to instruct serializer to do it  correctly so RavenDB can understand it as DateTime?

Example LocalDateTime serialized into RavenDB data record:
```
 "dateStart": {
        "hour": 9,
        "minute": 27,
        "nano": 436000000,
        "second": 15,
        "dayOfMonth": 17,
        "dayOfWeek": "MONDAY",
        "dayOfYear": 260,
        "month": "SEPTEMBER",
        "monthValue": 9,
        "year": 2018,
        "chronology": {
            "id": "ISO",
            "calendarType": "iso8601"
        }
},
```

**Comment by ml054** [comment]
Hi, 

Support for serializing jdk8 extra types is not enabled by default. 

Please add dependency:
```
<dependency>
     <groupId>com.fasterxml.jackson.datatype</groupId>
     <artifactId>jackson-datatype-jsr310</artifactId>
     <version>2.9.6</version>
</dependency>
```

Then register module:

    store.getConventions().getEntityMapper().registerModule(new JavaTimeModule());

And you can save LocalDateTime or LocalDate. 

Sample:

     @Test
     public void canSerializeDate() throws Exception {
        try (IDocumentStore store = new DocumentStore("http://localhost:8080", "db1")) {
            store.initialize();

            store.getConventions().getEntityMapper().registerModule(new JavaTimeModule());

            try (IDocumentSession newSession = store.openSession()) {
                User2 user1 = new User2();
                user1.setLocalDate(LocalDate.now());
                user1.setName("Marcin");
                user1.setLocalDateTime(LocalDateTime.now());
                newSession.store(user1, "users/1");
                newSession.saveChanges();
            }
        }
    }

Saved document:

![image](https://user-images.githubusercontent.com/1250431/45921652-c057b200-beb9-11e8-9d3e-bf90b3732572.png)


More information about custom serialization module:  https://github.com/FasterXML/jackson-modules-java8

**Comment by dmarko484** [comment]
Implemented, working great!! thanks.
