### ISSUE TITLE
NullPointerException in RavenServerRunner.run

### ISSUE THREAD

**Issue by JohannesRudolph** [ravendb/jvm-client#14]
I tried the `RavenTestDriver' with the example from the docs and was immediately greated by an NPE. 

The culprit appears to be L:93 `processBuilder.directory().getAbsolutePath()` as .directory() returns null. 
The source annotation for ProcessBuilder.directory notes

```java
    /**
     * Returns this process builder's working directory.
     *
     * Subprocesses subsequently started by this object's {@link
     * #start()} method will use this as their working directory.
     * The returned value may be {@code null} -- this means to use
     * the working directory of the current Java process, usually the
     * directory named by the system property {@code user.dir},
     * as the working directory of the child process.
     *
     * @return this process builder's working directory
     */
```

The exception handling code should thus handle null correctly, it's a pity not to see the original error because the exception handler throws an NPE...

**Comment by ml054** [comment]
Moving this issue to our bug tracker: 

https://issues.hibernatingrhinos.com/issue/RDBC-292
