### ISSUE TITLE
RavenTestDriver: EINVAL when opening /tmp/

### ISSUE THREAD

**Issue by JohannesRudolph** [ravendb/jvm-client#15]
After fighting to get .net core 2.1.5 installed to run RavenTestDriver, running a plain `RavenTestDriver.getDocumentStore()` greets me with this exception:

```
12:26:22.048 [main] INFO  net.ravendb.embedded.EmbeddedServer - Starting global server

java.lang.IllegalStateException: Unable to start the RavenDB Server
Output:
       _____                       _____  ____ 
      |  __ \                     |  __ \|  _ \ 
      | |__) |__ ___   _____ _ __ | |  | | |_) |
      |  _  // _` \ \ / / _ \ '_ \| |  | |  _ < 
      | | \ \ (_| |\ V /  __/ | | | |__| | |_) |
      |_|  \_\__,_| \_/ \___|_| |_|_____/|____/ 


      Safe by default, optimized for efficiency

 Build 41010, Version 4.1, SemVer 4.1.4, Commit dc2e9e3
 PID 25343, 64 bits, 12 Cores, Phys Mem 31.293 GBytes, Arch: X64
 Source Code (git repo): https://github.com/ravendb/ravendb
 Built with love by Hibernating Rhinos and awesome contributors!
+---------------------------------------------------------------+


Raven.Client.Exceptions.Server.ServerLoadFailureException: Failed to load system storage 
At /tmp/1551871581612-1/System ---> System.InvalidOperationException: EINVAL when opening /tmp/1551871581612-1/System/Journals/0000000000000000000.journal
```

This is running on Fedora28. My `/tmp` is a tmpfs.

I then wanted to run a custom configuration to see whether putting the data dir on another filesystem will help. So I put up a nice 

```kotlin
    val testServerOptions = ServerOptions().apply {
      // specify where ravendb server should be extracted (optional)
      targetServerLocation = "/tmp/x-ravendb"
      dataDirectory = "/tmp/x-ravendb/data"
    }

    configureServer(testServerOptions)
```
but to no effect. Why? Well... 

```
    public static void configureServer(ServerOptions options) {
        if (TEST_SERVER_STORE.isValueCreated()) {
            throw new IllegalStateException("Cannot configure server after it was started. " +
                    "Please call 'configureServer' method before any 'getDocumentStore' is called.");
        }
    }
```
Apparently, `configureServer` doesn't do _anything_. It should probably set the serverOptions supplier... 

Sorry guys, but the first time experience I had with running RavenTestdriver has been absolutely horrendous so far. In order: 

- fix NPEs around `dotnet` not being installed #14 
- any way to make the ravendb-test-driver compatible with any .net 2.x or at least 2.1.x release? 2.1.5 is old, current is 2.1.8 and that forces me to through incantations with my package manager to get it installed
- the EINVAL looks scarry and has no hints on what to fix
- configureServer should... work?

**Comment by JohannesRudolph** [comment]
I can confirm that the server starts fine when the `targetServerLocation` is on an ext4.

tmpfs is extremely common for /tmp though. Any way you can make this work? I'll probably file this over on the ravendb issue tracker as this is not the fault of the jvm client.

**Comment by ml054** [comment]
@JohannesRudolph thanks for reporting that. Java setters for custom configuration was fixed. The remaining part is handling tempfs on linux. In general I'm afraid it will be hard to handle this file system + when we are creating temporary files we create this in "java.io.tmpdir" which usually points to /tmp. 

Anyway other solution might be to detect that user wants to run RavenDB server on not supported file system and warn about this, so then we can point to different path which points to ext4, or ntfs file system.

**Comment by JohannesRudolph** [comment]
thanks @ml054 for the quick fixes. let's continue figuring this out at https://issues.hibernatingrhinos.com/issue/RavenDB-13032

**Comment by ml054** [comment]
No problem, once we manage to fix and test that we can release new version to ease your development workflow.
