### ISSUE TITLE
Add ETL Operations to the client

### ISSUE THREAD

**Issue by JohannesRudolph** [ravendb/jvm-client#16]
See https://ravendb.net/docs/article-page/4.1/csharp/client-api/operations/maintenance/etl/add-etl

These are all missing from the jvm client

**Comment by ml054** [comment]
Sure, we can add those operations to java client.

**Comment by ml054** [comment]
https://issues.hibernatingrhinos.com/issue/RDBC-294

Moved issue to our bug tracker. @JohannesRudolph If you can open new issues on youtrack - that would be great.

**Comment by JohannesRudolph** [comment]
Ok, makes sense. Do you want to disable issues on github then and add an
entry to readme to direct users to youTrack?

Marcin Lewandowski <notifications@github.com> schrieb am Fr. 8. März 2019
um 10:51:

**Comment by ml054** [comment]
There is information about bug tracker in README.md ;)
This is why I think we should leave an ability to report issues here, as it is better to have issue in 'wrong' place then no reported issue.
