### ISSUE TITLE
waitForIndexesAfterSaveChanges() calls wrong overload? 

### ISSUE THREAD

**Issue by JohannesRudolph** [ravendb/jvm-client#17]
I was just browsing the source to figure out something, and noticed this: 

```java
    public void waitForIndexesAfterSaveChanges() {
        waitForReplicationAfterSaveChanges(options -> {
        });
    }
```
from: https://github.com/ravendb/ravendb-jvm-client/blob/5a45727de507b541d1571e79ddd97c7d88bee787/src/main/java/net/ravendb/client/documents/session/InMemoryDocumentSessionOperations.java#L1125

Shouldn't this call into `public void waitForIndexesAfterSaveChanges(Consumer<InMemoryDocumentSessionOperations.IndexesWaitOptsBuilder> options)` instead? 

Looks like a copy/paste error to me.

**Comment by ayende** [comment]
Yes, I believe that this is the case.

**Comment by ml054** [comment]
moved to our official bug tracker:
https://issues.hibernatingrhinos.com/issue/RDBC-329
