### ISSUE TITLE
Cancelled Operations do not raise OperationCancelledExceptions

### ISSUE THREAD

**Issue by JohannesRudolph** [ravendb/jvm-client#19]
https://github.com/ravendb/ravendb-jvm-client/blob/d7cbfc028e138a6b93a072a2e6793632bf8f11ed/src/main/java/net/ravendb/client/documents/operations/Operation.java#L49

There appears to be a typo in the code. The status returned by the server is: 

```json
{"$type":"Raven.Client.Documents.Operations.OperationState, Raven.Client","Progress":null,"Result":null,"Status":"Canceled"}
```

but the case has one `l` too many: 

```java
                case "Cancelled":
                    throw new OperationCancelledException();
```

I think this should be caught by a unit test or something.

**Comment by ml054** [comment]
fixed in https://github.com/ravendb/ravendb-jvm-client/commit/2925dbae14e795a9613f6ec00a70bc3853896fec
