### ISSUE TITLE
Error during use a certificate for store data

### ISSUE THREAD

**Issue by gustavodaquino** [ravendb/jvm-client#20]
**Expected Behavior**

Store a new document into Raven.

**Current Behavior**

Exception while try to use the certificate .pfx generated.

> Unable to find certificate for alias: '1'. If you generated certificate using RavenDB server, then it might be related to: https://github.com/dotnet/corefx/issues/30946. Please try to create Keystore using *.crt and *.key files instead of *.pfx.

**Steps to Reproduce**

The same found on wiki was used.

```
// load certificate
KeyStore clientStore = KeyStore.getInstance("PKCS12");
clientStore.load(new FileInputStream("c:\\ravendb\\client-cert.pfx"), "passwordToPfx".toCharArray());

try (DocumentStore store = new DocumentStore())  {
    store.setCertificate(clientStore);
    store.setDatabase("Northwind");
    store.setUrls(new String[]{ "https://my_secured_raven" });

    store.initialize();

    // do your work here
}
```

**Context (Environment)**

Windows 10
Spring Boot 2.2.6
OpenJDK 8

**Comment by ml054** [comment]
How did you generate client certificate? Using RavenDB server? 

Due to issue in corefx we need to create keystore using crt and key files instead of pfx. 

See here:
https://github.com/ravendb/ravendb-jvm-client/blob/4f11f8024a1dde43db02514cbbedbcd1fb2304c1/src/test/java/net/ravendb/client/test/client/HttpsTest.java#L188

**Comment by gustavodaquino** [comment]
Thanks, @ml054, worked like a charm. But it could have a smooth way to achieve this using the SDK itself. I'm glad for your help.

**Comment by ayende** [comment]
@ml054 Can we provide a utility method to handle this? So we can just expose `getX509Certificate(crt, key)` ?

**Comment by ml054** [comment]
@ayende yes I will add extra method to easily deal with this issue and make our client's live easier.

**Comment by ml054** [comment]
reported in our official bug tracker: https://issues.hibernatingrhinos.com/issue/RDBC-408
