### ISSUE TITLE
Scala support

### ISSUE THREAD

**Issue by dwlizlo** [ravendb/jvm-client#21]
Currently RavenDB requires Java beans which makes it hard to work with Scala.
I'm not sure if there are any plans for supporting Scala, but would you be willing to accept PRs making JVM client more extensible?

Something that would make it possible to inject your own json serializer/deserializer would be a good start though.

**Comment by ml054** [comment]
Hi @dwlizlo , 

Could you elaborate what problem you are trying to solve? 

If I understand correctly you want to be able to serialize / deserialize entities with scala specific props, right? If so, then you can register custom module to jackson serialization (ie. https://github.com/FasterXML/jackson-module-scala). 

You can access Entity mapper via: https://github.com/ravendb/ravendb-jvm-client/blob/667085a687930402eab66d6676fdd324c2c91dc5/src/main/java/net/ravendb/client/documents/conventions/DocumentConventions.java#L146
and customize to suite your needs.

**Comment by dwlizlo** [comment]
Hey @ml054, gonna be honest - I didn't expect response so fast. :)

setEntityMapper worked like a charm 🎉
