### ISSUE TITLE
Kotlin deserialization - SOLVED

### ISSUE THREAD

**Issue by davidmoshal** [ravendb/jvm-client#24]
Certain Kotlin classes will fail to deserialize, for example one without an empty constructor:
```kt
class Doctor(var name: String)
```

The solution is to set the store's entity mapper to one that understands Kotlin.
For example:

```kt
import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import net.ravendb.client.documents.DocumentStore
import net.ravendb.client.documents.IDocumentStore

class Doctor(var name: String)

val mapper = jacksonObjectMapper().apply {
    configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
}

 val store: IDocumentStore = .... 
store.conventions.entityMapper = mapper
store.initialize()
```

Note: the FAIL_ON_UNKNOWN_PROPERTIES configuration is to prevent failure with the document's `@metadata` property.

NOTE: the setEntityMapper appears to be undocumented, ie: a search of the RavenDB site for 'mapper' returns no hits.

**Comment by ayende** [comment]
Created an issue to document it: https://issues.hibernatingrhinos.com/issue/RDoc-1958
