### ISSUE TITLE
NullPointerException from SubscriptionWorker

### ISSUE THREAD

**Issue by vijayakumarsuraj** [ravendb/jvm-client#39]
Calling `addOnUnexpectedSubscriptionError` on a `SubscriptionWorker` throws a `NullPointerException` because the `onUnexpectedSubscriptionError` field is never initialized.

Because of this any unexpected errors encountered by the worker also end-up throwing a `NullPointerException` (when `EventHelper.invoke(onUnexpectedSubscriptionError, ex)` is called). 

I'm on JDK 11 using v5.2.1 of the ravendb client.

**Comment by ml054** [comment]
Reported in our bugtracker: https://issues.hibernatingrhinos.com/issue/RDBC-529

**Comment by ml054** [comment]
Fixed in https://github.com/ravendb/ravendb-jvm-client/pull/40
