### ISSUE TITLE
SubscriptionWorker does not handle "redirects" correctly

### ISSUE THREAD

**Issue by vijayakumarsuraj** [ravendb/jvm-client#43]
Looks like the `SubscriptionWorker` isn't handling the `REDIRECT` connection status correctly. Seeing "_Could not redirect to null, because it was not found in local topology, even after retrying_" exceptions at regular intervals when consuming a data subscription.

A quick investigation led me to [this line](https://github.com/ravendb/ravendb-jvm-client/blob/v5.2/src/main/java/net/ravendb/client/documents/subscriptions/SubscriptionWorker.java#L358) in the `SubscriptionWorker` as being the culprit. It'll make `null` RedirectTag values into the string "null". Which in turn causes [shouldTryToReconnect](https://github.com/ravendb/ravendb-jvm-client/blob/53afe944fd1cfd1f54379e9e5e0f3c49308f8b36/src/main/java/net/ravendb/client/documents/subscriptions/SubscriptionWorker.java#L655-L670) to throw instead of returning `true`.

**Comment by ml054** [comment]
@vijayakumarsuraj You can track progress here: https://issues.hibernatingrhinos.com/issue/RDBC-538

**Comment by ml054** [comment]
@vijayakumarsuraj Does it happen on production or during running integration tests? How many nodes you have in your cluster / database group?

**Comment by ml054** [comment]
Fixed in 5.2.2

**Comment by vijayakumarsuraj** [comment]
> Does it happen on production or during running integration tests? How many nodes you have in your cluster / database group?

This was happening on our "Stage" server, which has 2 nodes.

**Comment by ml054** [comment]
Did it happen around creating/deleting subscriptions?

**Comment by vijayakumarsuraj** [comment]
No. It was happening while consuming the subscription.

**Comment by ml054** [comment]
Could you check that with 5.2.2?

**Comment by vijayakumarsuraj** [comment]
Sure! Is it pushed to Maven, because I can't see it there?

**Comment by ml054** [comment]
Released today, so it will take few hours for central to sync.
