### ISSUE TITLE
Non blocking client for Java

### ISSUE THREAD

**Issue by avillev** [ravendb/jvm-client#59]
I am scoping out this client's documentation and RavenDB's website and I do not see any mention of a non-blocking or reactive client.

Is this a feature of this client ? Or maybe another one ?

**Comment by ml054** [comment]
Hi, 

@avillev Currently we support synchronous client only.

**Comment by avillev** [comment]
Thank you for the quick response.

Is there any plan for it ?

**Comment by ml054** [comment]
As of now, rather no, but future will show. :)

**Comment by ml054** [comment]
No sure if this is an option but maybe you can use node js client instead - which is non-blocking: https://github.com/ravendb/ravendb-nodejs-client
