### ISSUE TITLE
Duplicate condition == dead code?

### ISSUE THREAD

**Issue by damccull** [ravendb/jvm-client#60]
Hello,

Looking through the library. This code is reported by vscode java plugin as dead. Just above it is another copy of the same code. Does this need to be duplicated like this or can it be removed?

https://github.com/ravendb/ravendb-jvm-client/blob/33031ebb25441c9ffe260957a804ad6d1f5e3975/src/main/java/net/ravendb/client/http/RequestExecutor.java#L712-L714

**Comment by ml054** [comment]
Hi, 
@damccull 

Yes it seems to be double check which is not needed. Thanks for catching this.

**Comment by damccull** [comment]
You're welcome.
