### ISSUE TITLE
Comment documentation welcome?

### ISSUE THREAD

**Issue by damccull** [ravendb/jvm-client#61]
As I'm reading through the library source and learning how it works, I'm adding comments to sections of code as well as javadoc comments to methods and classes. This is for me to help understand the code without forgetting how it works, creating easy reminders for myself.

Would the devs be interested in pull requests adding javadoc comments like this? https://github.com/damccull/ravendb-jvm-client/blob/documentation/src/main/java/net/ravendb/client/http/RequestExecutor.java#L281-L294

How about embedded comments within the code that explain the reason and/or workings behind sections of code that aren't obvious? I don't have any examples showing this at the moment, but I'm asking as a separate question so that I can tailor my commits  and branches according to the preferred PRs, should this be something that'd be welcomed.

**Comment by ayende** [comment]
Yes, we would gladly accept such PRs
