### ISSUE TITLE
Manually set up test server?

### ISSUE THREAD

**Issue by damccull** [ravendb/jvm-client#63]
Hello.  I'm trying to run the test suite on my local machine but I'm running under WSL, so no .exe exists to run in RAVENDB_JAVA_TEST_SERVER_PATH. Is there a way to skip that step and just run it against a server I manually set up and already have running?

**Comment by ml054** [comment]
Please point this variable to server path. Either exe or linux file. 

Please have a look here: 
https://github.com/ravendb/ravendb-jvm-client/blob/v5.4/.github/workflows/RavenClient.yml#L16

**Comment by ml054** [comment]
@damccull Does it help? Can we close?

**Comment by damccull** [comment]
Yes, thank you. Sorry, should have let you know before.
