### ISSUE TITLE
Can't Use UUID Field as Identifier (even though a uuid can be a string)

### ISSUE THREAD

**Issue by cmitchell** [ravendb/jvm-client#70]
Hi,

I think I've found a few bugs regarding setting the Identifier field.

https://ravendb.net/docs/article-page/5.4/java/server/kb/document-identifier-generation#guid shows that Guid (the C# version of a UUID) can be generated, but doesn't give an example of how to use it. The documentation for the java equivalent (UUID) seems to be missing entirely. 

https://ravendb.net/docs/article-page/5.4/csharp/client-api/document-identifiers/working-with-document-identifiers says that identifiers are always strings, but you must have C# selected. This same documentation should be provided if you have Java selected, but when java is selected nothing is shown.  (I found this by ggoogling)

So combining these two, I would think there's a way to use a `java.util.UUID` field as the identifier (and if there isn't, I would strongly encourage implementing this in order to be compatible with existing (legacy) data models).  UUID fields can be converted to strings (`toString()`) and made from strings (`UUID.fromString(value)`) so it wouldn't be difficult to implement if it does indeed only exist on the C# side, but not the java side. Jackson ObjectMpapers automatically recognize UUIDs for serialization and deserialization

Serialize -- put just the UUID back in to the field to send back to the user
```
Pattern UUID_REGEX =
  Pattern.compile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$");
(if field with @id or that is set as IdentifierField is of type UUID) {
 String potentialUuid = jsonNodeValue.substring([identityPartsSeparator} + 1)
    if (potentialUUID.matches()) {
         // set the field to UUID.fromString(potentialUUID)
     )  // throw an error
}
```

Call a UUID generator in the `store()` and set it on the UUID field so that the user has it immediately

Deserialize -- make the id compatible for use internally `
```
(if field with @id or that is set as IdentifierField is of type UUID) {
    // set it object.getSimpleName() + identityPartsSeparator + jsonNodeValue.toString()
}
```

**Comment by ayende** [comment]
Please note that GUID id is meant to be generated server side, and refers to the content of the id field, not its type.

We'll fix the issue with the missing doc, see: 
https://issues.hibernatingrhinos.com/issue/RDoc-2398/working-with-document-identifiers-page-for-Java-and-other-clients


We have supprot for custom serialization that you can use, see:
https://github.com/ravendb/ravendb-jvm-client/blob/v5.4/src/test/java/net/ravendb/client/test/client/CustomSerializationTest.java#L86

For identifier, you can control serialization at a granular level using:
https://github.com/ravendb/ravendb-jvm-client/blob/60b72cdb9345b8d13c61e2b2fc4325bd66d580f4/src/main/java/net/ravendb/client/documents/conventions/DocumentConventions.java#L345

**Comment by cmitchell** [comment]
@ayende Again, this is just another feature that would make the java client easier to use.  Whether I implement it in the ObjectMapper and then pass it in, verses the client doing this is a nice-to-have feature for developers that are provided by other database clients.

Ease of client use is certainly a factor when evaluating storage solutions.

**Comment by ayende** [comment]
I referenced this blog post earlier:
https://ayende.com/blog/188257-B/avoiding-non-string-identifiers-in-ravendb

There is an issue about ownership. We _enable_ this scenario, but this is something that experience have taught us leads to issues in some cases, and we want to be explicit about where we guide you toward the pit of success.
