### ISSUE TITLE
'Working with secured server' issue and resolution

### ISSUE THREAD

**Issue by gruendike** [ravendb/jvm-client#78]
I am connecting to our databases using SSL and was loading the certificate file as described under the section 'Working with secured server'.  After a bunch of troubleshooting the best output I was able to get was this error:

`javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

I don't know if this is always required, but in case anyone else runs into this problem I was able to fix it by exporting the certificate from Chrome using the option "Base64-encoded ASCII, certificate chain", and then importing this into Java's default keystore.  I couldn't find this step documented anywhere.  Thanks

**Comment by ml054** [comment]
Hi @gruendike 

How did you generate server certificate? How did you generate client certificate? What java version are you using? 

According to error I assume Java client can't trust the RavenDB server. Possible solution: Make sure Java has CA of RavenDB server certifite in its truststore.
