### ISSUE TITLE
Data subscriptions throw an IllegalStateException: "Session can only be opened once per each Subscription batch"

### ISSUE THREAD

**Issue by vijayakumarsuraj** [ravendb/jvm-client#90]
I am opening a single session per batch, but it looks like the batch object that is yielded to my _subscriber_ is the same instance each time (just containing the next set of items). 

In the c# client, [SubscriptionBatch.InitializeAsync](https://github.com/ravendb/ravendb/blob/713986adfb78f437e8fb1feb319107c18db87ecd/src/Raven.Client/Documents/Subscriptions/SubscriptionBatch.cs#L24) resets the `_sessionOpened` flag to false - which allows the subscriber to open a session against each _new_ batch. The Java client doesn't seem to be doing this.

I am using v6.0 (of client and server).

**Comment by ayende** [comment]
This indeed looks like a bug, yes. We need to add it. 
Can you send a Pull Request for this?

**Comment by vijayakumarsuraj** [comment]
I was unable to run tests locally or using Actions. I guess I am missing some setup steps...

Anyway, I have created the PR - https://github.com/ravendb/ravendb-jvm-client/pull/91. Needs some tests - but can't do that without a working build.

**Comment by ml054** [comment]
Thanks @vijayakumarsuraj  :)
